import './js/add-to-favorite';
import './js/adaptive-devices';
import './js/API/fetchAPI';
import './js/mobile-menu-favorites';
import './js/API/api-data-normalaizer';
import './js/switch-theme';
// import './js/header';
import './js/firebace/firebace-main';
import './js/switcher-mobile-menu';
import './js/btnToUp';
