import './js/adaptive-devices';
// import './js/API/fetchAPI';
// import './js/mobile-menu';
import './js/add-to-read';
import './js/API/fetchAPI';
import './js/mobile-menu';
import './js/loading';
import './js/API/api-data-normalaizer';
import './js/input-actions';
import './js/switch-theme';
import './js/newCalendar';
// import './js/weather';
import './js/categories-btns';
import './js/render news gallery/render-news-gallery';
// import './js/weather';
import './js/add-to-favorite';
import './js/header';
import './js/pagination';

import './js/firebace/firebace-main';
import './js/switcher-mobile-menu';
